#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive

installpkg(){
    dpkg-query --status $1 >/dev/null || apt-get install -y $1
}

add-apt-repository ppa:ondrej/php
apt-get update
installpkg zip
installpkg php7.0
installpkg php7.0-curl
installpkg php7.0-mbstring
installpkg php7.0-json
installpkg php7.0-mysql
installpkg php7.0-xml
installpkg php7.0-zip
#installpkg php7.0-redis
#installpkg redis-server
#installpkg supervisor
installpkg mysql-server

composer_install() {
    EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
    then
        >&2 echo 'ERROR: Invalid installer signature'
        rm composer-setup.php
        exit 1
    fi

    php composer-setup.php --quiet
    RESULT=$?
    rm composer-setup.php
#    exit $RESULT

    echo $RESULT;
}
composer_install

mv composer.phar /usr/local/bin/composer
cd /home/vagrant/crv_gs_githut
composer install -vv

#php bin/console server:run 127.0.0.1:8080